version: 2

models:
  - name: stg_ga4_events
    description: "Cleaned GA4 events from public dataset"
    columns:
      - name: event_id
        tests:
          - not_null
          - unique
      - name: user_pseudo_id
        tests:
          - not_null
      - name: event_timestamp
        tests:
          - not_null
      - name: event_name
        tests:
          - not_null
